services:
  local_server:
    build: .
    volumes:
      - ./dist:/usr/app/dist
      - ./public:/usr/app/public
      - ./src:/usr/app/src
      - ./tests:/usr/app/tests
      - ./package-lock.json:/usr/app/package-lock.json
      - ./package.json:/usr/app/package.json
      - ./tsconfig.json:/usr/app/tsconfig.json
      - ./webpack.config.js:/usr/app/webpack.config.js
    ports:
      - 8080:8080
